apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvdb-nfs
spec:
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /
    server: 10.0.2.123