apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvdb-nfs
spec:
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /
    server: fs-817c7500.efs.us-east-1.amazonaws.com