apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapp
  labels:
    app: users
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
      tier: frontend
  template:
    metadata:
      labels:
        app: users
        tier: frontend
    spec:
      containers:
      - name: users
        image: hshar/users
        ports:
        - containerPort: 8081
