apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp-sql
    tier: frontend
spec:
 containers:
 - name: users
   image: hshar/users
 - name: admin
   image: hshar/admin
